AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - lib/**/*.rb
    - test/**/*.rb
    - Gemfile
    - tobox.gemspec
  Exclude:
    - Rakefile
    - examples/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/EmptyBlock:
  Enabled: false
